### PR TITLE
Upload to the Forge

### PR DESCRIPTION
**Pull request by carlossg**
For issue #21, it'd be great to have the module in the Forge
With this commit you can just run `rake module:release` and will push to the Forge (after creating an account and the project page by hand)

### CODE REVIEW

**Comment by carlossg** [comment]
Forgot to mention that you need to configure your credentials in ~/.puppetforge.yml

```
--- 
forge: https://forge.puppetlabs.com
username: myuser
password: mypassword
```

https://github.com/maestrodev/puppet-blacksmith

**Comment by vStone** [comment]
Maybe you have a clue what to do with

```
Could not autoload puppet/face/module/install: Error converting value for param 'modulepath': Could not find value for $confdir
```

**Comment by carlossg** [comment]
is that running `rake test`? tests fail for me but with other errors with both 2.7.22 and 3.2.3.
Can you check in the Gemfile.lock to use the same gem versions?

```

  1) apache::mod::passenger with no passenger module with package => custom with provider => undef
     Failure/Error: it { should contain_apache__sys__modpackage('passenger').with_package('custom').with_provider(nil) }
     Puppet::Error:
       osfamily  not supported by the apache-module. add support in the params class and send a pull request ;) at /Users/csanchez/dev/maestrodev/puppet/apache/spec/fixtures/modules/apache/manifests/params.pp:211 on node carlos-mbook-pro.local
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions/fail.rb:3:in `block in <top (required)>'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:147:in `block (2 levels) in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:140:in `block in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/function.rb:42:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:15:in `block in evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `each'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/caseopt.rb:49:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/casestatement.rb:32:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:15:in `block in evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `each'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/resource/type.rb:137:in `evaluate_code'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/resource.rb:81:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:166:in `block in evaluate_classes'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:151:in `each'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:151:in `evaluate_classes'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions/include.rb:11:in `block in <top (required)>'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:147:in `block (2 levels) in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:140:in `block in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions/require.rb:34:in `block in <top (required)>'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:147:in `block (2 levels) in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/functions.rb:140:in `block in newfunction'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/function.rb:42:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:15:in `block in evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `each'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast/block_expression.rb:10:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/ast.rb:62:in `safeevaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/resource/type.rb:137:in `evaluate_code'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/resource.rb:81:in `evaluate'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:252:in `block (4 levels) in evaluate_definitions'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:251:in `block (3 levels) in evaluate_definitions'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:250:in `each'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:250:in `block (2 levels) in evaluate_definitions'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:249:in `block in evaluate_definitions'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/errors.rb:61:in `exceptwrap'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:248:in `evaluate_definitions'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:271:in `block (2 levels) in evaluate_generators'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:268:in `block in evaluate_generators'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:265:in `loop'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:265:in `evaluate_generators'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:103:in `block in compile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:103:in `compile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/parser/compiler.rb:29:in `compile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/indirector/catalog/compiler.rb:86:in `block in compile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler/none.rb:6:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/util/profiler.rb:26:in `profile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/indirector/catalog/compiler.rb:84:in `compile'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/indirector/catalog/compiler.rb:44:in `find'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/puppet-3.2.3/lib/puppet/indirector/indirection.rb:197:in `find'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-puppet-0.1.6/lib/rspec-puppet/support.rb:24:in `build_catalog_without_cache'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-puppet-0.1.6/lib/rspec-puppet/support.rb:30:in `build_catalog'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-puppet-0.1.6/lib/rspec-puppet/example/class_example_group.rb:59:in `catalogue'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-puppet-0.1.6/lib/rspec-puppet/example/class_example_group.rb:7:in `subject'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.14.4/lib/rspec/core/memoized_helpers.rb:68:in `should'
     # ./spec/classes/apache_mod_passenger__spec.rb:35:in `block (5 levels) in <top (required)>'

  2) apache::mod::passenger with no passenger module with package => custom with provider => custom should contain Apache::Sys::Modpackage[passenger] with package => "custom" and provider => "custom"
     Failure/Error: it { should contain_apache__sys__modpackage('passenger').with_package('custom').with_provider('custom') }
       expected that the catalogue would contain Apache::Sys::Modpackage[passenger] with provider set to `"custom"` but it is set to `nil` in the catalogue
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/handler.rb:36:in `handle_matcher'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.14.4/lib/rspec/core/memoized_helpers.rb:68:in `should'
     # ./spec/classes/apache_mod_passenger__spec.rb:40:in `block (5 levels) in <top (required)>'

  3) apache::mod::passenger with no passenger module with package => undef with provider => undef on centos should contain Apache::Sys::Modpackage[passenger] with package => "passenger" and provider => "gem"
     Failure/Error: it { should contain_apache__sys__modpackage('passenger').with_package('passenger').with_provider('gem') }
       expected that the catalogue would contain Apache::Sys::Modpackage[passenger] with package set to `"passenger"` but it is set to `"mod_passenger"` in the catalogue, and parameter provider set to `"gem"` but it is set to `nil` in the catalogue
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/handler.rb:36:in `handle_matcher'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.14.4/lib/rspec/core/memoized_helpers.rb:68:in `should'
     # ./spec/classes/apache_mod_passenger__spec.rb:49:in `block (6 levels) in <top (required)>'

  4) apache::mod::passenger with no passenger module with package => undef with provider => undef on debian should contain Apache::Sys::Modpackage[passenger] with package => "libapache2-mod-passenger" and provider => "apt"
     Failure/Error: it { should contain_apache__sys__modpackage('passenger').with_package('libapache2-mod-passenger').with_provider('apt') }
       expected that the catalogue would contain Apache::Sys::Modpackage[passenger] with provider set to `"apt"` but it is set to `nil` in the catalogue
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-expectations-2.14.0/lib/rspec/expectations/handler.rb:36:in `handle_matcher'
     # /Users/csanchez/.rvm/gems/ruby-1.9.3-p429/gems/rspec-core-2.14.4/lib/rspec/core/memoized_helpers.rb:68:in `should'
     # ./spec/classes/apache_mod_passenger__spec.rb:53:in `block (6 levels) in <top (required)>'

Finished in 1.86 seconds
32 examples, 4 failures
```

**Comment by vStone** [comment]
No, that was when running the rake module:push task :)

**Comment by carlossg** [comment]
my bad, opening a new pull request to fix that

**Pull request merged**
